---
- name: Installs and configures CloudWatch Tools
  hosts: all
  sudo: true
  
  roles:
    - common
    - cw_disk
    - cw_memory

  vars_prompt:
    aws_access_key_id: "AWS Access Key ID"
    aws_secret_access_key: "AWS Secret Key"
