---
- name: Install PyCurl
  apt: pkg=python-pycurl state=present update_cache=yes cache_valid_time=300

- name: Copy Docker APT repo public key
  copy: src=docker.asc dest=/etc/docker.asc
      
- name: Import Docker APT Key
  apt_key: file=/etc/docker.asc state=present 

- name: Docker APT Config
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present

- name: Install Saucy Kernel
  apt: pkg=linux-image-generic-lts-saucy state=present update_cache=yes cache_valid_time=300
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'
      
- name: Install Saucy Kernel Headers
  apt: pkg=linux-headers-generic-lts-saucy state=present update_cache=yes cache_valid_time=300
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'

- name: Install Docker
  apt: pkg=lxc-docker state=latest update_cache=yes

