- name: Installs Apache Mesos
  sudo: true
  hosts: all
  roles:
    - mesos
  vars:
      zk_mesos: localhost:2181/mesos
      master_attributes:
        - { name: zone, value: default }
        - { name: region, value: default }
      slave_attributes:
        - { name: zone, value: default }
        - { name: region, value: default }
