---
- name: Install Boto
  apt: pkg=python-boto state=present update_cache=yes cache_valid_time=300

- name: Setup Boto Config
  template: src=boto.cfg.j2 dest=/etc/boto.cfg mode=600 owner=root group=root
